# Hari 1 – Pandas Introduction

## Numpy Attributes

In [1]:
import numpy as np

my_numpy = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,0]
                    ])
print(my_numpy)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [2]:
# dimensi
my_numpy.ndim

2

In [3]:
# shape
my_numpy.shape

(2, 5)

In [4]:
# type
my_numpy.dtype

dtype('int32')

In [5]:
# itemsize
my_numpy.itemsize

4

In [6]:
# nbytes
my_numpy.nbytes

40

## Indexing Arrays

In [7]:
my_numpy[1][2:]

array([8, 9, 0])

### Slicing Array

In [8]:
# [start : stop :step]
nmp = np.array(range(10))
print(nmp)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
nmp[0:6:2]

array([0, 2, 4])

In [10]:
# multidimension 
my_numpy[1:,2:]

array([[8, 9, 0]])

## Reshaping Array

In [11]:
my_numpy.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

### Joining Array

In [12]:
my_numpy = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,0]
                    ])

nmpy = np.array([
                [1,2,3,1,4], 
                [2,3,5,3,5]
                ])

np.concatenate([my_numpy, nmpy])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 3, 1, 4],
       [2, 3, 5, 3, 5]])

## Objek Pandas : Series vs DataFrame

### Series

In [13]:
import pandas as pd

x = pd.Series([6,3,4,6])
print(x)

0    6
1    3
2    4
3    6
dtype: int64


In [14]:
# mengubah sumbu/index
# cara pertama
x.index = ['a', 'b', 'c', 'd']
print(x)

a    6
b    3
c    4
d    6
dtype: int64


In [15]:
# cara kedua
x = pd.Series([6,3,4,6], index=['a', 'b', 'c', 'd'])
print(x)

a    6
b    3
c    4
d    6
dtype: int64


In [16]:
# check tipe data
print(type(x))

<class 'pandas.core.series.Series'>


### DataFrame

In [17]:
import pandas as pd

df = pd.DataFrame({'tipe_int': [50, 21], 'tipe_string': ['a', 'b']})
print(df)

   tipe_int tipe_string
0        50           a
1        21           b


In [18]:
# check tipe data
print(type(df))

<class 'pandas.core.frame.DataFrame'>


## Membaca data dari File 

In [24]:
# membaca dari dari csv
df_from_csv = pd.read_csv('Data COVID-19 Jawa Barat.csv')

In [25]:
# membaca dari dari csv
df_from_csv = pd.read_csv('Data COVID-19 Jawa Barat.csv')

## Pemeriksaan Sederhana Tentang Karakteristik Data 

In [26]:
df_from_csv = pd.read_csv('Data COVID-19 Jawa Barat.csv')

In [27]:
df_from_csv.head(7)

tanggal  kode_prov            nama_prov  kode_kab            nama_kab  \
0  2020-08-01         32  Provinsi Jawa Barat      3277         KOTA CIMAHI   
1  2020-08-01         32  Provinsi Jawa Barat      3217  KAB. BANDUNG BARAT   
2  2020-08-01         32  Provinsi Jawa Barat      3203        KAB. CIANJUR   
3  2020-08-01         32  Provinsi Jawa Barat      3276          KOTA DEPOK   
4  2020-08-01         32  Provinsi Jawa Barat      3209        KAB. CIREBON   
5  2020-08-01         32  Provinsi Jawa Barat      3207         KAB. CIAMIS   
6  2020-08-01         32  Provinsi Jawa Barat      3275         KOTA BEKASI   

   closecontact  closecontact_dikarantina  closecontact_discarded  suspect  \
0             0                         0                       0        0   
1             0                         0                       0        0   
2             0                         0                       0        0   
3             0                         0                       0        0   
4             0                         0                       0        0   
5             0                         0                       0        0   
6             0                         0                       0        0   

   suspect_diisolasi  ...  pertumbuhan_suspect_discarded  \
0                  0  ...                              0   
1                  0  ...                              0   
2                  0  ...                              0   
3                  0  ...                              0   
4                  0  ...                              0   
5                  0  ...                              0   
6                  0  ...                              0   

   pertumbuhan_suspect_diisolasi  pertumbuhan_probable  \
0                              0                     0   
1                              0                     0   
2                              0                     0   
3                              0                     0   
4                              0                     0   
5                              0                     0   
6                              0                     0   

   pertumbuhan_probable_discarded  pertumbuhan_probable_diisolasi  \
0                               0                               0   
1                               0                               0   
2                               0                               0   
3                               0                               0   
4                               0                               0   
5                               0                               0   
6                               0                               0   

   pertumbuhan_probable_meninggal  pertumbuhan_confirmation  \
0                               0                         1   
1                               0                         1   
2                               0                         0   
3                               0                         8   
4                               0                         0   
5                               0                         0   
6                               0                         3   

   pertumbuhan_confirmation_selesai  pertumbuhan_confirmation_meninggal  \
0                                 0                                   0   
1                                 0                                   0   
2                                 0                                   0   
3                                 0                                   0   
4                                 0                                   0   
5                                 0                                   0   
6                                 0                                   0   

   Unnamed: 31  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  

[7 row

In [29]:
df_from_csv.tail(5)

tanggal  kode_prov            nama_prov  kode_kab          nama_kab  \
9011  2021-06-18         32  Provinsi Jawa Barat      3214   KAB. PURWAKARTA   
9012  2021-06-18         32  Provinsi Jawa Barat      3202     KAB. SUKABUMI   
9013  2021-06-18         32  Provinsi Jawa Barat      3278  KOTA TASIKMALAYA   
9014  2021-06-18         32  Provinsi Jawa Barat      3216       KAB. BEKASI   
9015  2021-06-18         32  Provinsi Jawa Barat      3211     KAB. SUMEDANG   

      closecontact  closecontact_dikarantina  closecontact_discarded  suspect  \
9011          4824                      2938                    1886     2766   
9012         11832                     10027                    1805    11059   
9013         12812                     12370                     442     2659   
9014         28205                     23210                    4995    18741   
9015          4440                      3057                    1383     1917   

      suspect_diisolasi  ...  pertumbuhan_suspect_discarded  \
9011               1936  ...                              0   
9012              10332  ...                              0   
9013               2610  ...                              0   
9014              12078  ...                              0   
9015                956  ...                              0   

      pertumbuhan_suspect_diisolasi  pertumbuhan_probable  \
9011                              0                     0   
9012                              0                     0   
9013                              0                     0   
9014                              0                     0   
9015                              0                     0   

      pertumbuhan_probable_discarded  pertumbuhan_probable_diisolasi  \
9011                               0                               0   
9012                               0                               0   
9013                               0                               0   
9014                               0                               0   
9015                               0                               0   

      pertumbuhan_probable_meninggal  pertumbuhan_confirmation  \
9011                               0                         2   
9012                               0                        10   
9013                               0                        10   
9014                               0                       148   
9015                               0                       202   

      pertumbuhan_confirmation_selesai  pertumbuhan_confirmation_meninggal  \
9011                                 5                                   0   
9012                                 0                                   0   
9013                               132                                   0   
9014                                 0                                   0   
9015                                 0                                   0   

      Unnamed: 31  
9011          NaN  
9012          NaN  
9013          NaN  
9014          NaN  
9015          NaN  

[5 rows x 32 columns]

In [30]:
df_from_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9016 entries, 0 to 9015
Data columns (total 32 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   tanggal                               9016 non-null   object 
 1   kode_prov                             9016 non-null   int64  
 2   nama_prov                             9016 non-null   object 
 3   kode_kab                              9016 non-null   int64  
 4   nama_kab                              9016 non-null   object 
 5   closecontact                          9016 non-null   int64  
 6   closecontact_dikarantina              9016 non-null   int64  
 7   closecontact_discarded                9016 non-null   int64  
 8   suspect                               9016 non-null   int64  
 9   suspect_diisolasi                     9016 non-null   int64  
 10  suspect_discarded                     9016 non-null   int64  
 11  probable         

In [31]:
df_from_csv.describe()

kode_prov     kode_kab  closecontact  closecontact_dikarantina  \
count     9016.0  9016.000000   9016.000000               9016.000000   
mean        32.0  3115.928571   7959.792147               6097.102484   
std          0.0   600.476288  10805.391749               9321.015733   
min         32.0     0.000000      0.000000                  0.000000   
25%         32.0  3206.750000   1113.500000                601.000000   
50%         32.0  3213.500000   3261.000000               2105.000000   
75%         32.0  3272.250000  10598.000000               7408.000000   
max         32.0  3279.000000  55849.000000              49289.000000   

       closecontact_discarded       suspect  suspect_diisolasi  \
count             9016.000000   9016.000000        9016.000000   
mean              1862.689663   4305.467280        3277.370674   
std               2015.057649   4809.280089        4011.510008   
min                  0.000000      0.000000           0.000000   
25%                311.000000   1094.750000         597.000000   
50%               1107.000000   2251.500000        1533.000000   
75%               2547.750000   6255.000000        5409.000000   
max               7731.000000  22153.000000       18896.000000   

       suspect_discarded     probable  probable_diisolasi  ...  \
count        9016.000000  9016.000000         9016.000000  ...   
mean          931.401176   101.955524           50.488576  ...   
std          1311.359381   239.595782          163.294858  ...   
min             0.000000     0.000000            0.000000  ...   
25%            61.000000     6.000000            0.000000  ...   
50%           417.000000    31.000000            1.000000  ...   
75%          1038.000000    78.000000           19.000000  ...   
max          6312.000000  1695.000000         1191.000000  ...   

       pertumbuhan_suspect_discarded  pertumbuhan_suspect_diisolasi  \
count                    9016.000000                    9016.000000   
mean                       16.117125                       4.033163   
std                       191.782354                      60.437096   
min                         0.000000                       0.000000   
25%                         0.000000                       0.000000   
50%                         0.000000                       0.000000   
75%                         0.000000                       0.000000   
max                      7690.000000                    4001.000000   

       pertumbuhan_probable  pertumbuhan_probable_discarded  \
count            9016.00000                     9016.000000   
mean                0.53272                        0.298026   
std                 5.21898                        4.101624   
min                 0.00000                        0.000000   
25%                 0.00000                        0.000000   
50%                 0.00000                        0.000000   
75%                 0.00000                        0.000000   
max               287.00000                      268.000000   

       pertumbuhan_probable_diisolasi  pertumbuhan_probable_meninggal  \
count                     9016.000000                     9016.000000   
mean                         0.078749                        0.155945   
std                          0.707623                        2.297911   
min                          0.000000                        0.000000   
25%                          0.000000                        0.000000   
50%                          0.000000                        0.000000   
75%                          0.000000                        0.000000   
max                         25.000000                      163.000000   

       pertumbuhan_confirmation  pertumbuhan_confirmation_selesai  \
count               9016.000000                       9016.000000   
mean                  37.036713                         33.846606   
std                   99.519964                        101.879089   
min              